# Generated by Django 4.2.1 on 2023-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
