# Generated by Django 4.2.1 on 2023-05-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="attatchment",
            field=models.FileField(default=None, upload_to="uploads/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="image_attatchment",
            field=models.ImageField(default=None, upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
