# Generated by Django 4.2.1 on 2023-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(null=True)),
                ('category', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('see', models.IntegerField(default='0')),
                ('file', models.FileField(null=True, upload_to='uploads/')),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
