# Generated by Django 4.2.1 on 2023-05-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ordered_food', models.CharField(max_length=100)),
                ('ordered_from', models.CharField(max_length=200)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
