# Generated by Django 4.2.1 on 2023-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_orders_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='number',
            new_name='number_of_food_ordered',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderer',
            field=models.CharField(default=1, max_length=20, verbose_name='주문자명'),
            preserve_default=False,
        ),
    ]
