# Generated by Django 4.2.1 on 2023-05-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_number_orders_number_of_food_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='additional_request',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderer',
            field=models.CharField(max_length=20),
        ),
    ]
