# Generated by Django 4.2.1 on 2023-05-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_orders_additional_request_alter_orders_ordered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ordered_at',
            new_name='ordered_time',
        ),
    ]
