# Generated by Django 4.2.1 on 2023-05-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_rename_ordered_at_orders_ordered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='upload',
        ),
    ]
