# Generated by Django 4.2.1 on 2023-05-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_remove_orders_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
