# Generated by Django 4.2.1 on 2023-05-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_orders_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_time',
        ),
    ]
