# Generated by Django 4.2.1 on 2023-05-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_orders_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='additional_request',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_from',
            field=models.CharField(max_length=256),
        ),
    ]
