# Generated by Django 4.2.1 on 2023-05-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_updates_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
