# Generated by Django 4.2.1 on 2023-05-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=12, null=True)),
                ('level', models.IntegerField(null=True)),
                ('log_in_at', models.DateTimeField(auto_now_add=True)),
                ('pw_change_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('sign_up_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
