# Generated by Django 4.2.1 on 2023-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_active_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='pic/', verbose_name='증명사진'),
        ),
    ]
